# Generated by Django 4.1.7 on 2023-03-30 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название категории')),
                ('icon', models.ImageField(upload_to='category/', verbose_name='Изображение категории')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ChoiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория разновидности товара')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя типа товара цвет/вкус')),
                ('icon', models.ImageField(upload_to='choices/', verbose_name='Главное изображение разновидности товара')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Колличество товара')),
                ('choices_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.choicecategory')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название общих изображений товаров')),
                ('all_icon', models.ImageField(upload_to='all_icon/', verbose_name='Общие изображения товаров')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название товара')),
                ('price', models.PositiveIntegerField(verbose_name='Цена товара')),
                ('hot', models.BooleanField(default=False, verbose_name='Популярное')),
                ('discount', models.BooleanField(default=False, verbose_name='Наличие скидки')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опбуликовано')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('all_icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.icon', verbose_name='Все изображения товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.category', verbose_name='Категория товара')),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.choices', verbose_name='Название подкатегории')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specifications', models.TextField(max_length=555, verbose_name='Характеристики')),
                ('equipment', models.TextField(max_length=555, verbose_name='Комплектация')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('N', 'New'), ('W', 'Waiting'), ('C', 'Cancel'), ('R', 'Ready pay'), ('D', 'On delivery'), ('Dd', 'Delivered')], max_length=50, verbose_name='Статус заказа')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=155, null=True, verbose_name='Имя пользователя')),
                ('bio', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/profile/', verbose_name='Фото профиля')),
                ('vk', models.CharField(blank=True, max_length=50, null=True, verbose_name='Профиль вконтакте')),
                ('inst', models.CharField(blank=True, max_length=50, null=True, verbose_name='Профиль в инсте')),
                ('telegram', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка телеграм')),
                ('favourites', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.item', verbose_name='Избранное')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.order', verbose_name='Заказ')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='info_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.iteminfo', verbose_name='Основная информация о товаре'),
        ),
    ]
