# Generated by Django 4.1.7 on 2023-03-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='choicecategory',
            options={'ordering': ['id'], 'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterModelOptions(
            name='choices',
            options={'ordering': ['id'], 'verbose_name': 'Разновидность товара', 'verbose_name_plural': 'Разновидности товаров'},
        ),
        migrations.AlterModelOptions(
            name='icon',
            options={'ordering': ['id'], 'verbose_name': 'Изображения товара', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-date'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='iteminfo',
            options={'ordering': ['id'], 'verbose_name': 'Описание товара', 'verbose_name_plural': 'Описания товаров'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id'], 'verbose_name': 'Статус заказа', 'verbose_name_plural': 'Статусы заказов'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['id'], 'verbose_name': 'Профиль юзера', 'verbose_name_plural': 'Профили юзеров'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='all_icon',
        ),
        migrations.RemoveField(
            model_name='item',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favourites',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='order',
        ),
        migrations.AddField(
            model_name='item',
            name='all_icon',
            field=models.ManyToManyField(blank=True, null=True, to='myApp.icon', verbose_name='Все изображения товара'),
        ),
        migrations.AddField(
            model_name='item',
            name='choice',
            field=models.ManyToManyField(blank=True, null=True, to='myApp.choices', verbose_name='Название подкатегории'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, null=True, to='myApp.item', verbose_name='Избранное'),
        ),
        migrations.AddField(
            model_name='profile',
            name='order',
            field=models.ManyToManyField(blank=True, null=True, to='myApp.order', verbose_name='Заказ'),
        ),
    ]
