# Generated by Django 4.1.7 on 2023-03-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_category_options_alter_choicecategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='choices_name',
        ),
        migrations.AddField(
            model_name='choices',
            name='choices_name',
            field=models.ManyToManyField(to='myApp.choicecategory', verbose_name='Имя подкатегории'),
        ),
    ]
