# Generated by Django 4.1.7 on 2023-03-31 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_remove_choices_choices_name_choices_choices_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='choices_name',
        ),
        migrations.AddField(
            model_name='choices',
            name='choices_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.choicecategory', verbose_name='Имя подкатегории'),
            preserve_default=False,
        ),
    ]
