# Generated by Django 4.1.7 on 2023-03-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_remove_choices_choices_name_choices_choices_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='choice',
            field=models.ManyToManyField(blank=True, null=True, related_name='item_as_choice', to='myApp.choices', verbose_name='Название подкатегории'),
        ),
    ]
