# Generated by Django 4.1.7 on 2023-03-31 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_alter_item_all_icon_alter_profile_favourites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.profile', verbose_name='Владелец поста'),
            preserve_default=False,
        ),
    ]
