# Generated by Django 4.1.7 on 2023-03-31 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_item_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='date',
            new_name='created_at',
        ),
    ]
